Airline_Reservation/urls.py
from django.conf.urls import url
from . import views
app_name='Airline_Reservation'

urlpatterns = [
    url('^$',views.login,name='login_page'),
    url('about/',views.about,name='about_page'),
    url('signup/',views.signup,name='signup_page'),
    url('homepage/',views.homepage,name='home_page'),
    url('logout/',views.logout,name='logout_page'),
    url('back/',views.back,name='back_page'),
    url('forgotpassword/',views.forgotpassword,name='forgot_password_page'),
    url('bookingform/',views.bookingform,name='booking_form'),
    url('bookingpage/(?P<flight_id>[−\w]+)/$', views.bookingpage,name='booking_page'),
    url('reservationdetails/', views.reservationdetails,name='reservation_page'),
    url('fulldetails/(?P<user>[−\w]+)/$', views.fulldetails,name='full_details'),
    url('deletedetails/(?P<user>[−\w]+)/$', views.deletedetails,name='delete_details'),
    
]

OSTL_Project/urls.py
from django.contrib import admin
from django.conf.urls import url,include


urlpatterns = [
    url(r'^',include('Airline_Reservation.urls')),
    url(r'^admin/',admin.site.urls),

]

Airline_Reservation/models.py
from django.db import models


class Airplane_Details(models.Model):
    Airlines=models.CharField(max_length=50)
    Source=models.CharField(max_length=20)
    Destination=models.CharField(max_length=20)
    Departure_Time=models.CharField(max_length=10)
    Arrival_Time=models.CharField(max_length=10)
    Seats=models.IntegerField()
    Fare_Type=models.CharField(max_length=10)
    Price=models.IntegerField()


class Reservation_Details(models.Model):
    key=models.ForeignKey("Airplane_Details",on_delete=models.CASCADE,null=True)
    Name=models.CharField(max_length=20,null=True)
    Email=models.EmailField(null=True)
     
    Flight_Date=models.DateField(null=True) 
    Returning_Date=models.DateField(null=True)
    Adults=models.IntegerField(null=True)
    Children=models.IntegerField()
    Status=models.BooleanField(default=True)

Airline_Reservation/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from .models import Airplane_Details,Reservation_Details

def login(request):
    if request.user.is_authenticated:
        return redirect('http://127.0.0.1:8000/homepage')

    else:    
        if request.method == 'POST':
            username =request.POST['username']
            password =request.POST['password']

            User = auth.authenticate(username=username,password=password)

            if User is not None: # username and password exits and is correct
                auth.login(request,User)
                return redirect('homepage/')
            else:
                messages.info(request,'Invalid Details')
                # return redirect('/')

    return render(request,"login.html",{'title':'Login Page'})


def about(request):
    return render(request,"about.html",{'title':'About Page'})

def signup(request):

    if request.method == 'POST':
        username =request.POST['username']
        email =request.POST['email']
        password1 =request.POST['password1']
        password2 =request.POST['password2']
        
        if(password1==password2):
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username Taken')
                return redirect('http://127.0.0.1:8000/signup/')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'Email Taken')
                return redirect('http://127.0.0.1:8000/signup/')
            else:    
                new_user = User.objects.create_user(username=username,email=email,password=password1)
                new_user.save()
                messages.info(request,'User Created')
        else:
            messages.info(request,'Password did not match')
            return redirect('http://127.0.0.1:8000/signup/')
        return redirect('/')    
    else:        
        return render(request,"signup.html",{'title':'Signup Page'})    


def logout(request):
    auth.logout(request);
    return redirect('/')

def homepage(request):
    return render(request, "homepage.html",{'title':'Home Page'})

def back(request):
    return redirect('http://127.0.0.1:8000/homepage/')

def forgotpassword(request):
    if request.method == 'POST':
        username =request.POST['username']
        newpassword =request.POST['newpassword']
        email=request.POST['email']
        
        if User.objects.filter(username=username,email=email).exists():
            u = User.objects.get(username=username)
            u.set_password(newpassword)
            u.save()
            messages.info(request,'Password Changed')
            return redirect('http://127.0.0.1:8000/forgotpassword/')

        else:
            messages.info(request,'Username or email not found!!!')
            return render(request,"forgotpassword.html")
        
    else:
        return render(request,"forgotpassword.html")

def bookingform (request):
    if request.method =='POST':
       
            if request.POST['Show flights']=='Show flights':

                            
                source=request.POST['source']
                destination=request.POST['destination']
                faretype=request.POST['FareType']
                                                                                                                            
                details = Airplane_Details.objects.filter(Source=source).filter(Destination=destination).filter(Fare_Type=faretype)
               
                return render(request,"flightdetails.html",{'details':details})

    return render(request,"bookingform.html")


def bookingpage(request,flight_id):
    current_user = request.user
   
    if request.method == 'POST':
        data=Reservation_Details()
        data.Name=request.POST['name']
        data.Email =current_user.email
        data.Adults=request.POST.get('adult',0)
        data.Children = request.POST.get('children')
        data.Flight_Date=request.POST['departing']
        data.Returning_Date=request.POST['returning']
        data.key_id=flight_id
    
        data.save()
        return render(request,"homepage.html",{'user':current_user})   
    return render(request,"bookingpage.html",{'user':current_user})


def reservationdetails(request):
    current_user = request.user
    
    users=Reservation_Details.objects.filter(Email=current_user.email)


    return render(request,"reservationdetails.html",{'users':users})


def fulldetails(request,user):
    user_info=Reservation_Details.objects.get(id=user)
    flight_info = Airplane_Details.objects.get(id=user_info.key_id)

    print(user_info.Status)
    price =int(flight_info.Price)
    adults= int(user_info.Adults)
    children=int(user_info.Children)
    Total_price=price*adults+price*children
    

    return render(request,"fulldetails.html",{'user':user_info,'fl':flight_info,'price':Total_price})    


def deletedetails(request,user):
    user_info=Reservation_Details.objects.get(id=user)
    flight_info = Airplane_Details.objects.get(id=user_info.key_id)

    user_info.Status=False
    user_info.save()

    
    return render(request,"homepage.html")

templates/about.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <div class="topnav">
            <h1>Airline Reservation System</h1>
            <a href={% url 'Airline_Reservation:back_page' %}>Back</a>
            <a href={% url 'Airline_Reservation:logout_page' %}>Logout</a>
            <a><h4>Hello {{ user.username}}</h4></a>
            </div>

{% else %}
    <div class="topnav">
            <h1>Airline Reservation System</h1>
            <a href={% url 'Airline_Reservation:signup_page' %}>Signup</a>
            <a href={% url 'Airline_Reservation:login_page' %}>Login</a>
            </div>
{% endif%}
<style>marquee{
    height:630px;
    padding:10px;
    font-size:100px
    }
</style>
<marquee direction="down" >
    <h1>Airline reservation systems incorporate airline schedules, fare tariffs, passenger reservations and ticket records.</h1?
    <h1>Using these web services on airline reservation system interface, the information for the airline availability and pricing can be published on a user friend GUI interface. End user can select the flight and proceed for the booking.</h1>
</marquee> 
{% endblock %}

templates/base.html
{% load  static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">

        
        
       
</head>
<body>
    
    {% block content%}

    {% endblock %}
</body>
</html>

templates/bookingform.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bookingform.css' %}">
    <link rel="stylesheet" type="text/css"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


</head>

<body>
    <form method='POST' action=".">
    {% csrf_token %}
    <div class="booking-form-box" style="align:center">

    <h1>Search Flights</h1>
        {% comment %} <div class="radio-btn">
            <input type="radio" class="btn" name="way" checked="checked"><span>Roundtrip</span>
            <input type="radio" class="btn" name="way"> <span>One Way</span>
            <input type="radio" class="btn" name="way"> <span> Multi-City</span>
        </div> {% endcomment %}

        <div>
            <div class="booking-form">
                <label>Flying From </label>
                <input type="text" class="form-control" placeholder="City or Airport" name='source'>
                <label>Flying To </label>
                <input type="text" class="form-control" placeholder="City or Airport" name='destination'>

                {% comment %} <div class="input-grp">
                    <label> Departing </label>
                    <input type="date" class="form-control select-date" name="departing" data-date-split-input="true">
                </div>
                <div class="input-grp">
                    <label> Returning </label>
                    <input type="date" class="form-control select-date" name="returning" data-date-split-input="true"> {% endcomment %}
                {% comment %} </div>
                <div class="input-grp">
                    <label>Adults </label>
                    <input type="number" class="form-control" value="1">
                </div>
                <div class="input-grp">
                    <label> Children </label>
                    <input type="number" class="form-control" value="0">
                </div> {% endcomment %}

                <div class="input-grp">
                    <label> Travel Class</label>
                    <select class="custom-select" id="FareType" name="FareType">
                        <option value="Economy">Economy Class</option>
                        <option value="Business">Business Class</option>
                    </select>
                </div>
                <div class="input-grp">
                <input type="submit" class="btn btn-primary flight" value='Show flights' name='Show flights'>
                </div>

            </div>
        </div>
    </div>
    </form>



</body>

</html>

templates/bookingpage.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bookingform.css' %}">
    <link rel="stylesheet" type="text/css"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


</head>

<body>
    <form method='POST' action=".">
    {% csrf_token %}
    <div class="booking-form-box" style="align:center">

    <h1>Search Flights</h1>
        {% comment %} <div class="radio-btn">
            <input type="radio" class="btn" name="way" checked="checked"><span>Roundtrip</span>
            <input type="radio" class="btn" name="way"> <span>One Way</span>
            <input type="radio" class="btn" name="way"> <span> Multi-City</span>
        </div> {% endcomment %}
        
        <div>
            <div class="booking-form">
                <label>Name </label>
                <input type="text" class="form-control" placeholder="Name" name='name'>
                <label>Email </label>
                <input type="text" class="form-control" placeholder="Email" name='email' value={{user.email}} disabled>

                <div class="input-grp">
                    <label> Departing </label>
                    <input type="date" class="form-control select-date" name="departing" placeholder="DD-MM-YYYY" data-date-split-input="true">
                </div> 
                <div class="input-grp">
                    <label> Returning </label>
                    <input type="date" class="form-control select-date" name="returning" data-date-split-input="true"> 
                </div>
                <div class="input-grp">
                    <label>Adults </label>
                    <input type="number" class="form-control" value="1" min="1" max="3" name="adult">
                </div> 
                <div class="input-grp">
                    <label> Children </label>
                    <input type="number" class="form-control" value="0" min="0" max="3" name="children">
                </div> 

                {% comment %} <div class="input-grp">
                    <label> Travel Class</label>
                    <select class="custom-select" id="FareType" name="FareType">
                        <option value="Economy">Economy Class</option>
                        <option value="Business">Business Class</option>
                    </select>
                </div> {% endcomment %}

                <div class="input-grp">
                <input type="submit" class="btn btn-primary flight" value='Book Ticket' name='Book Ticket'>
                </div>

            </div>
        </div>
    </div>
    </form>


   <h1> </h1>


</body>

</html>

templates/flightdetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flight Details</title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

       
</head>
<body>


<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Source</th>
      <th scope="col">Destination</th>
      <th scope="col">Airlines</th>
      <th scope="col">Departure Time</th>
      <th scope="col">Arrival Time</th>
      <th scope="col">Fare</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for detail in details %}
    <tr>
      <td>{{detail.Source}}</td>
      <td>{{detail.Destination}}</td>
      <td>{{detail.Airlines}}</td>
      <td>{{detail.Departure_Time}}</td>
      <td>{{detail.Arrival_Time}}</td>
      <td>{{detail.Fare_Type}}</td>
      <td>{{detail.Price}}</td>
       {% csrf_token %}
        <td  ><a class="btn btn-success" href="{% url 'Airline_Reservation:booking_page' flight_id=detail.id %}">Book Now</a></td>
    </tr>
{% endfor %}
  </tbody>
</table>

</body>
</html>

templates/forgotpassword.html
{% extends 'base.html' %}
{% load  static  %}
    
    {%   block content  %}
    
        <div class="topnav">
        <h1>Airline Reservation System</h1>
        <a href={% url 'Airline_Reservation:login_page' %}>Login</a>
        <a href={% url 'Airline_Reservation:signup_page' %}>Signup</a>
        <a href={% url 'Airline_Reservation:about_page' %}>About</a>
        </div>


        <div class="login-box" >
        <h1>Reset Password</h1>
        <form  method='POST'>
            {%  csrf_token %}
            <p>Username</p>
            <input type="text" placeholder="Enter Username" name='username'>
            <p>Email</p>
            <input type="email" placeholder="Enter Email" name='email'>
            <p> New Password</p>
            <input type="password" placeholder="Enter New Password" name='newpassword'> 
            <!-- <a href="#">Forget Password</a> -->
            <input type="submit" value="Reset Password">
        <div>
            {% for message in messages%}
            {{message}}
            {% endfor%}
       </div>
        </form>
    </div>
{% endblock  %}

        

templates/fulldetails.html
{% comment %} {% load static%} {% endcomment %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flight Details</title>

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</head>

<body>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>  
      <th scope="col">Email</th>
      <th scope="col">Airlines</th>
      <th scope="col">Source</th>
      <th scope="col">Destination</th>
      <th scope="col">Departure Time</th>
      <th scope="col">Arrival Time</th>
      <th scope="col">Flight Date</th>
      <th scope="col">Return Date</th>
      <th scope="col">Adults</th>
      <th scope="col">Children</th>
      <th scope="col">Fare Type</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
    </tr>
  </thead>
 
  {% if user.Status == True %}
  <tbody>
    <tr>
    <td>{{user.Name}}</td>
    <td>{{user.Email}}</td>
    <td>{{fl.Airlines}}</td>
    <td>{{fl.Source}}</td>
    <td>{{fl.Destination}}</td>
    <td>{{fl.Departure_Time}}</td>
    <td>{{fl.Arrival_Time}}</td>
    <td>{{user.Flight_Date}}</td>
    <td>{{user.Returning_Date}}</td>
    <td>{{user.Adults}}</td>
    <td>{{user.Children}}</td>
    <td>{{fl.Fare_Type}}</td>
    <td>{{price}}</td>
    {% csrf_token %}
        <td><a  class="btn btn-warning" href="{% url 'Airline_Reservation:delete_details' user=user.id  %}">Cancel</a></td>
        <tr>
        </tbody>
  {% else %}
   <tbody>
    <tr>
    <td>{{user.Name}}</td>
    <td>{{user.Email}}</td>
    <td>{{fl.Airlines}}</td>
    <td>{{fl.Source}}</td>
    <td>{{fl.Destination}}</td>
    <td>{{fl.Departure_Time}}</td>
    <td>{{fl.Arrival_Time}}</td>
    <td>{{user.Flight_Date}}</td>
    <td>{{user.Returning_Date}}</td>
    <td>{{user.Adults}}</td>
    <td>{{user.Children}}</td>
    <td>{{fl.Fare_Type}}</td>
    <td>{{price}}</td>
    {% csrf_token %}
        <td>Cancelled</td>
       
    </tr>
     </tbody>
  {% endif%}
  
</table>




</body>
</html>



    

  
</body>

</html>

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flight Details</title>

        {% comment %} <link rel="stylesheet" type="text/css" href="homepage.css"> {% endcomment %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>

<body>

<div class="topnav" style="background-color: black;">
        <h1>Airline Reservation System</h1>
      
        <a href={% url 'Airline_Reservation:logout_page' %}>Logout</a>
        <a href={% url 'Airline_Reservation:about_page' %}>About</a>
        <a><h4>Hello {{ user.username}}</h4></a>
</div>

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'css/Plane2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'css/Plane3.jpg' %}" class="d-block w-100" alt="...">
    
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<section class="py-5" >
  <div class="container" >
    <a href="{% url 'Airline_Reservation:booking_form' %}"><button type="button" class="btn btn-primary btn-lg" >Book Tickets</button></a>
    <a href="{% url 'Airline_Reservation:reservation_page' %}"> <button type="button" class="btn btn-secondary btn-lg" >View Booked Tickets</button></a>
  </div>
</section>

</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load  static  %}
    
    {%   block content  %}
    
        <div class="topnav">
        <h1>Airline Reservation System</h1>
        <a href={% url 'Airline_Reservation:signup_page' %}>Signup</a>
        <a href={% url 'Airline_Reservation:about_page' %}>About</a>
        </div>


        <div class="login-box" >
        <h1>Login Page</h1>
        <form  method='POST'>
            {%  csrf_token %}
            <p>Username</p>
            <input type="text" placeholder="Enter Username" name='username'>
            <p>Password</p>
            <input type="password" placeholder="Enter Password" name='password'>
            <a href="{% url 'Airline_Reservation:forgot_password_page' %}" class="pass">Forgot Password</a> 
            <!-- <a href="#">Forget Password</a> -->
            <input type="submit" value="Login">
            
            <div class="account">Don't have an account <a href={% url 'Airline_Reservation:signup_page'%}>SignUp?</a></div>
             <div>
       {% for message in messages%}
       {{message}}
       {% endfor%}
       </div> 
        </form>
    </div>
   
{% endblock  %}

        

templates/printdetails.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking form</title>
    
</head>

<body>
<h1>{{date}}</h1>

</body>
</html>

templates/reservationdetails.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation Details</title>

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</head>

<body>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Adults</th>
      <th scope="col">Children</th>
      <th scope="col">Flight Date</th>
      <th scope="col">Return Date</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr>
      <td>{{user.Name}}</td>
      <td>{{user.Email}}</td>
      <td>{{user.Adults}}</td>
      <td>{{user.Children}}</td>
      <td>{{user.Flight_Date}}</td>
      <td>{{user.Returning_Date}}</td>
      <form method ="POST"  >
         {% csrf_token %}
        <td><a  class="btn btn-success" href="{% url 'Airline_Reservation:full_details' user=user.id  %}">View Details</a></td>
        
    </form>    
    </tr>
{% endfor %}
  </tbody>
</table>








</body>

</html>

templates/signup.html
{% extends 'base.html' %}

{% block content %}

 <div class="topnav">
        <h1>Airline Reservation System</h1>
        <a href={% url 'Airline_Reservation:about_page' %}>About</a>
        <a href={% url 'Airline_Reservation:login_page' %}>Login</a>
        </div>

 <div class="login-box">
        <h1>SignUp</h1>
        <form method='POST'>
            {% csrf_token %}      
            <p>Email</p>
            <input type="email" placeholder="Enter Email" name='email'>
            <p>Username</p>
            <input type="text" placeholder="Enter Username" name='username'>
            <p>Password</p>
            <input type="password" placeholder="Create Password" name='password1'>
            <p>Conform Password</p>
            <input type="password" placeholder="Conform Password" name='password2'>
            <input type="submit" value="SignUp">
            <div class="tanmay">Already have an account <a href={% url 'Airline_Reservation:login_page'%}>Login?</a></div> <br>
       <div>
       {% for message in messages%}
       {{message}}
       {% endfor%}
       </div>
{% endblock %}